import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import { Fredoka } from "next/font/google";
import "./globals.css";
import ConvexClientProvider from "@/components/ConvexClientProvider";
import { Header } from "@/components/header";

const fredoka = Fredoka({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Mamish App",
  description: "Generated by create next app",
  icons: {
    icon: "/cat.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning dir="rtl">
      <body className={`${fredoka.className} select-none flex flex-col bg-gradient-to-br from-slate-200 to-slate-400`}>
        <ThemeProvider attribute="class">
          <ConvexClientProvider>
            <Header />
            <main className="h-full flex flex-col justify-center items-center">
              {children}
            </main>
          </ConvexClientProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
